global:
  imagePullPolicy: IfNotPresent
  kafka:
    bootstrapServers: "kafka:9092"
    topic: "ticket-events"

zookeeper:
  image: confluentinc/cp-zookeeper:7.3.2
  replicas: 1
  resources:
    requests:
      cpu: "100m"
      memory: "500Mi"
    limits:
      cpu: "100m"
      memory: "500Mi"

kafka:
  image: confluentinc/cp-kafka:7.3.2
  replicas: 1
  brokerId: 1
  resources:
    requests:
      cpu: "100m"
      memory: "500Mi"
    limits:
      cpu: "100m"
      memory: "500Mi"
  persistence:
    enabled: false
    size: 5Gi

apiGateway:
  image:
    repository: ghcr.io/kseniamuhina/api-gateway
    tag: "v0.1.1-amd64"
  replicas: 1
  service:
    type: ClusterIP
    port: 8000
  ingress:
    enabled: false
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: service-hub.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: tls-secret
        hosts:
          - service-hub.example.com
  env:
    ticketServiceUrl: "http://ticket-service:8001"
  resources:
    requests:
      cpu: "100m"
      memory: "200Mi"
    limits:
      cpu: "200m"
      memory: "300Mi"

ticketService:
  image:
    repository: ghcr.io/kseniamuhina/ticket-service
    tag: "v0.1.1-amd64"
  replicas: 1
  service:
    type: ClusterIP
    port: 8001
  env:
    db:
      host: "79.174.89.43"
      port: 18809
      name: "team4_db"
      user: "team4"
    kafkaBootstrapServers: "kafka:9092"
  resources:
    requests:
      cpu: "100m"
      memory: "300Mi"
    limits:
      cpu: "200m"
      memory: "500Mi"

notificationService:
  image:
    repository: ghcr.io/kseniamuhina/notification-service
    tag: "v0.1.1-amd64"
  replicas: 1
  service:
    type: ClusterIP
    port: 8002
  env:
    kafkaBootstrapServers: "kafka:9092"
  resources:
    requests:
      cpu: "100m"
      memory: "200Mi"
    limits:
      cpu: "200m"
      memory: "300Mi"
